# Generated by Django 6.0.3 on 2026-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productreview_productreviewhelpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
