# Generated by Django 6.0.3 on 2026-03-07 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopfollower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopToShopFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops_following', to='shop.shop')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_followers', to='shop.shop')),
            ],
            options={
                'unique_together': {('following', 'follower_shop')},
            },
        ),
    ]
