# Generated by Django 6.0.3 on 2026-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0002_issue_issuemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='stage',
            field=models.CharField(choices=[('open', 'Open'), ('replied', 'Replied'), ('seller_resolved', 'Pending Confirmation'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20),
        ),
    ]
