# Generated by Django 6.0.3 on 2026-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow_app', '0003_alter_issue_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('shipped', 'Shipped'), ('receipt_confirmed', 'Receipt Confirmed'), ('funds_released', 'Funds Released'), ('dispute_opened', 'Dispute Opened'), ('refunded', 'Refunded'), ('issue_reported', 'Issue Reported'), ('issue_replied', 'Issue Replied'), ('issue_resolved', 'Issue Resolved'), ('issue_escalated', 'Issue Escalated')], max_length=30),
        ),
    ]
